spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.5:3306/xymaill_oms
    driver-class-name: com.mysql.jdbc.Driver
  application:
        name: nacos-maill-order
  cloud:
       nacos:
         discovery:
            server-addr: localhost:8848

    #?????????????
server-url:
  nacos-user-service: http://maill-order

server:
  port: 9000

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0


